// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: custom_event.proto

package object_builder_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CustomEventServiceClient is the client API for CustomEventService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CustomEventServiceClient interface {
	Create(ctx context.Context, in *CreateCustomEventRequest, opts ...grpc.CallOption) (*CustomEvent, error)
	GetList(ctx context.Context, in *GetCustomEventsListRequest, opts ...grpc.CallOption) (*GetCustomEventsListResponse, error)
	GetSingle(ctx context.Context, in *CustomEventPrimaryKey, opts ...grpc.CallOption) (*CustomEvent, error)
	Update(ctx context.Context, in *CustomEvent, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Delete(ctx context.Context, in *CustomEventPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type customEventServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCustomEventServiceClient(cc grpc.ClientConnInterface) CustomEventServiceClient {
	return &customEventServiceClient{cc}
}

func (c *customEventServiceClient) Create(ctx context.Context, in *CreateCustomEventRequest, opts ...grpc.CallOption) (*CustomEvent, error) {
	out := new(CustomEvent)
	err := c.cc.Invoke(ctx, "/object_builder_service.CustomEventService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEventServiceClient) GetList(ctx context.Context, in *GetCustomEventsListRequest, opts ...grpc.CallOption) (*GetCustomEventsListResponse, error) {
	out := new(GetCustomEventsListResponse)
	err := c.cc.Invoke(ctx, "/object_builder_service.CustomEventService/GetList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEventServiceClient) GetSingle(ctx context.Context, in *CustomEventPrimaryKey, opts ...grpc.CallOption) (*CustomEvent, error) {
	out := new(CustomEvent)
	err := c.cc.Invoke(ctx, "/object_builder_service.CustomEventService/GetSingle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEventServiceClient) Update(ctx context.Context, in *CustomEvent, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.CustomEventService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *customEventServiceClient) Delete(ctx context.Context, in *CustomEventPrimaryKey, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/object_builder_service.CustomEventService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CustomEventServiceServer is the server API for CustomEventService service.
// All implementations must embed UnimplementedCustomEventServiceServer
// for forward compatibility
type CustomEventServiceServer interface {
	Create(context.Context, *CreateCustomEventRequest) (*CustomEvent, error)
	GetList(context.Context, *GetCustomEventsListRequest) (*GetCustomEventsListResponse, error)
	GetSingle(context.Context, *CustomEventPrimaryKey) (*CustomEvent, error)
	Update(context.Context, *CustomEvent) (*emptypb.Empty, error)
	Delete(context.Context, *CustomEventPrimaryKey) (*emptypb.Empty, error)
	mustEmbedUnimplementedCustomEventServiceServer()
}

// UnimplementedCustomEventServiceServer must be embedded to have forward compatible implementations.
type UnimplementedCustomEventServiceServer struct {
}

func (UnimplementedCustomEventServiceServer) Create(context.Context, *CreateCustomEventRequest) (*CustomEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedCustomEventServiceServer) GetList(context.Context, *GetCustomEventsListRequest) (*GetCustomEventsListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetList not implemented")
}
func (UnimplementedCustomEventServiceServer) GetSingle(context.Context, *CustomEventPrimaryKey) (*CustomEvent, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSingle not implemented")
}
func (UnimplementedCustomEventServiceServer) Update(context.Context, *CustomEvent) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedCustomEventServiceServer) Delete(context.Context, *CustomEventPrimaryKey) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedCustomEventServiceServer) mustEmbedUnimplementedCustomEventServiceServer() {}

// UnsafeCustomEventServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CustomEventServiceServer will
// result in compilation errors.
type UnsafeCustomEventServiceServer interface {
	mustEmbedUnimplementedCustomEventServiceServer()
}

func RegisterCustomEventServiceServer(s grpc.ServiceRegistrar, srv CustomEventServiceServer) {
	s.RegisterService(&CustomEventService_ServiceDesc, srv)
}

func _CustomEventService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCustomEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEventServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.CustomEventService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEventServiceServer).Create(ctx, req.(*CreateCustomEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEventService_GetList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCustomEventsListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEventServiceServer).GetList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.CustomEventService/GetList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEventServiceServer).GetList(ctx, req.(*GetCustomEventsListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEventService_GetSingle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEventPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEventServiceServer).GetSingle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.CustomEventService/GetSingle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEventServiceServer).GetSingle(ctx, req.(*CustomEventPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEventService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEvent)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEventServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.CustomEventService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEventServiceServer).Update(ctx, req.(*CustomEvent))
	}
	return interceptor(ctx, in, info, handler)
}

func _CustomEventService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CustomEventPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CustomEventServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/object_builder_service.CustomEventService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CustomEventServiceServer).Delete(ctx, req.(*CustomEventPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// CustomEventService_ServiceDesc is the grpc.ServiceDesc for CustomEventService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CustomEventService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "object_builder_service.CustomEventService",
	HandlerType: (*CustomEventServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _CustomEventService_Create_Handler,
		},
		{
			MethodName: "GetList",
			Handler:    _CustomEventService_GetList_Handler,
		},
		{
			MethodName: "GetSingle",
			Handler:    _CustomEventService_GetSingle_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _CustomEventService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _CustomEventService_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "custom_event.proto",
}
