// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: bCalculationTable.proto

package mongo_document_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BuildingCalculationTableServiceClient is the client API for BuildingCalculationTableService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BuildingCalculationTableServiceClient interface {
	Upsert(ctx context.Context, in *BuildingCalculationTable, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *ById, opts ...grpc.CallOption) (*BuildingCalculationTable, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type buildingCalculationTableServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBuildingCalculationTableServiceClient(cc grpc.ClientConnInterface) BuildingCalculationTableServiceClient {
	return &buildingCalculationTableServiceClient{cc}
}

func (c *buildingCalculationTableServiceClient) Upsert(ctx context.Context, in *BuildingCalculationTable, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mongo_document_service.BuildingCalculationTableService/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildingCalculationTableServiceClient) Get(ctx context.Context, in *ById, opts ...grpc.CallOption) (*BuildingCalculationTable, error) {
	out := new(BuildingCalculationTable)
	err := c.cc.Invoke(ctx, "/mongo_document_service.BuildingCalculationTableService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildingCalculationTableServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mongo_document_service.BuildingCalculationTableService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *buildingCalculationTableServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mongo_document_service.BuildingCalculationTableService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BuildingCalculationTableServiceServer is the server API for BuildingCalculationTableService service.
// All implementations must embed UnimplementedBuildingCalculationTableServiceServer
// for forward compatibility
type BuildingCalculationTableServiceServer interface {
	Upsert(context.Context, *BuildingCalculationTable) (*emptypb.Empty, error)
	Get(context.Context, *ById) (*BuildingCalculationTable, error)
	Delete(context.Context, *ById) (*emptypb.Empty, error)
	UpdateStatus(context.Context, *UpdateStatusReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedBuildingCalculationTableServiceServer()
}

// UnimplementedBuildingCalculationTableServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBuildingCalculationTableServiceServer struct {
}

func (UnimplementedBuildingCalculationTableServiceServer) Upsert(context.Context, *BuildingCalculationTable) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedBuildingCalculationTableServiceServer) Get(context.Context, *ById) (*BuildingCalculationTable, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedBuildingCalculationTableServiceServer) Delete(context.Context, *ById) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedBuildingCalculationTableServiceServer) UpdateStatus(context.Context, *UpdateStatusReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedBuildingCalculationTableServiceServer) mustEmbedUnimplementedBuildingCalculationTableServiceServer() {
}

// UnsafeBuildingCalculationTableServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BuildingCalculationTableServiceServer will
// result in compilation errors.
type UnsafeBuildingCalculationTableServiceServer interface {
	mustEmbedUnimplementedBuildingCalculationTableServiceServer()
}

func RegisterBuildingCalculationTableServiceServer(s grpc.ServiceRegistrar, srv BuildingCalculationTableServiceServer) {
	s.RegisterService(&BuildingCalculationTableService_ServiceDesc, srv)
}

func _BuildingCalculationTableService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuildingCalculationTable)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingCalculationTableServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.BuildingCalculationTableService/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingCalculationTableServiceServer).Upsert(ctx, req.(*BuildingCalculationTable))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildingCalculationTableService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingCalculationTableServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.BuildingCalculationTableService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingCalculationTableServiceServer).Get(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildingCalculationTableService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingCalculationTableServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.BuildingCalculationTableService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingCalculationTableServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _BuildingCalculationTableService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BuildingCalculationTableServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.BuildingCalculationTableService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BuildingCalculationTableServiceServer).UpdateStatus(ctx, req.(*UpdateStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BuildingCalculationTableService_ServiceDesc is the grpc.ServiceDesc for BuildingCalculationTableService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BuildingCalculationTableService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongo_document_service.BuildingCalculationTableService",
	HandlerType: (*BuildingCalculationTableServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _BuildingCalculationTableService_Upsert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _BuildingCalculationTableService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _BuildingCalculationTableService_Delete_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _BuildingCalculationTableService_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bCalculationTable.proto",
}
