// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: verificationActMongo.proto

package mongo_document_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VerificationActServiceClient is the client API for VerificationActService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VerificationActServiceClient interface {
	Upsert(ctx context.Context, in *VerificationAct, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Get(ctx context.Context, in *ById, opts ...grpc.CallOption) (*VerificationAct, error)
	Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*emptypb.Empty, error)
	UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type verificationActServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVerificationActServiceClient(cc grpc.ClientConnInterface) VerificationActServiceClient {
	return &verificationActServiceClient{cc}
}

func (c *verificationActServiceClient) Upsert(ctx context.Context, in *VerificationAct, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mongo_document_service.VerificationActService/Upsert", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationActServiceClient) Get(ctx context.Context, in *ById, opts ...grpc.CallOption) (*VerificationAct, error) {
	out := new(VerificationAct)
	err := c.cc.Invoke(ctx, "/mongo_document_service.VerificationActService/Get", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationActServiceClient) Delete(ctx context.Context, in *ById, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mongo_document_service.VerificationActService/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *verificationActServiceClient) UpdateStatus(ctx context.Context, in *UpdateStatusReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/mongo_document_service.VerificationActService/UpdateStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VerificationActServiceServer is the server API for VerificationActService service.
// All implementations must embed UnimplementedVerificationActServiceServer
// for forward compatibility
type VerificationActServiceServer interface {
	Upsert(context.Context, *VerificationAct) (*emptypb.Empty, error)
	Get(context.Context, *ById) (*VerificationAct, error)
	Delete(context.Context, *ById) (*emptypb.Empty, error)
	UpdateStatus(context.Context, *UpdateStatusReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedVerificationActServiceServer()
}

// UnimplementedVerificationActServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVerificationActServiceServer struct {
}

func (UnimplementedVerificationActServiceServer) Upsert(context.Context, *VerificationAct) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedVerificationActServiceServer) Get(context.Context, *ById) (*VerificationAct, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedVerificationActServiceServer) Delete(context.Context, *ById) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVerificationActServiceServer) UpdateStatus(context.Context, *UpdateStatusReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateStatus not implemented")
}
func (UnimplementedVerificationActServiceServer) mustEmbedUnimplementedVerificationActServiceServer() {
}

// UnsafeVerificationActServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VerificationActServiceServer will
// result in compilation errors.
type UnsafeVerificationActServiceServer interface {
	mustEmbedUnimplementedVerificationActServiceServer()
}

func RegisterVerificationActServiceServer(s grpc.ServiceRegistrar, srv VerificationActServiceServer) {
	s.RegisterService(&VerificationActService_ServiceDesc, srv)
}

func _VerificationActService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerificationAct)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationActServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.VerificationActService/Upsert",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationActServiceServer).Upsert(ctx, req.(*VerificationAct))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationActService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationActServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.VerificationActService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationActServiceServer).Get(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationActService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ById)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationActServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.VerificationActService/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationActServiceServer).Delete(ctx, req.(*ById))
	}
	return interceptor(ctx, in, info, handler)
}

func _VerificationActService_UpdateStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStatusReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VerificationActServiceServer).UpdateStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mongo_document_service.VerificationActService/UpdateStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VerificationActServiceServer).UpdateStatus(ctx, req.(*UpdateStatusReq))
	}
	return interceptor(ctx, in, info, handler)
}

// VerificationActService_ServiceDesc is the grpc.ServiceDesc for VerificationActService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VerificationActService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mongo_document_service.VerificationActService",
	HandlerType: (*VerificationActServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Upsert",
			Handler:    _VerificationActService_Upsert_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _VerificationActService_Get_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VerificationActService_Delete_Handler,
		},
		{
			MethodName: "UpdateStatus",
			Handler:    _VerificationActService_UpdateStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "verificationActMongo.proto",
}
