// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: email.proto

package auth_service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// EmailOtpServiceClient is the client API for EmailOtpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EmailOtpServiceClient interface {
	Create(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Email, error)
	GetEmailByID(ctx context.Context, in *EmailOtpPrimaryKey, opts ...grpc.CallOption) (*Email, error)
}

type emailOtpServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEmailOtpServiceClient(cc grpc.ClientConnInterface) EmailOtpServiceClient {
	return &emailOtpServiceClient{cc}
}

func (c *emailOtpServiceClient) Create(ctx context.Context, in *Email, opts ...grpc.CallOption) (*Email, error) {
	out := new(Email)
	err := c.cc.Invoke(ctx, "/auth_service.EmailOtpService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *emailOtpServiceClient) GetEmailByID(ctx context.Context, in *EmailOtpPrimaryKey, opts ...grpc.CallOption) (*Email, error) {
	out := new(Email)
	err := c.cc.Invoke(ctx, "/auth_service.EmailOtpService/GetEmailByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EmailOtpServiceServer is the server API for EmailOtpService service.
// All implementations must embed UnimplementedEmailOtpServiceServer
// for forward compatibility
type EmailOtpServiceServer interface {
	Create(context.Context, *Email) (*Email, error)
	GetEmailByID(context.Context, *EmailOtpPrimaryKey) (*Email, error)
	mustEmbedUnimplementedEmailOtpServiceServer()
}

// UnimplementedEmailOtpServiceServer must be embedded to have forward compatible implementations.
type UnimplementedEmailOtpServiceServer struct {
}

func (UnimplementedEmailOtpServiceServer) Create(context.Context, *Email) (*Email, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedEmailOtpServiceServer) GetEmailByID(context.Context, *EmailOtpPrimaryKey) (*Email, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetEmailByID not implemented")
}
func (UnimplementedEmailOtpServiceServer) mustEmbedUnimplementedEmailOtpServiceServer() {}

// UnsafeEmailOtpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EmailOtpServiceServer will
// result in compilation errors.
type UnsafeEmailOtpServiceServer interface {
	mustEmbedUnimplementedEmailOtpServiceServer()
}

func RegisterEmailOtpServiceServer(s grpc.ServiceRegistrar, srv EmailOtpServiceServer) {
	s.RegisterService(&EmailOtpService_ServiceDesc, srv)
}

func _EmailOtpService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Email)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailOtpServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.EmailOtpService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailOtpServiceServer).Create(ctx, req.(*Email))
	}
	return interceptor(ctx, in, info, handler)
}

func _EmailOtpService_GetEmailByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailOtpPrimaryKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EmailOtpServiceServer).GetEmailByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth_service.EmailOtpService/GetEmailByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EmailOtpServiceServer).GetEmailByID(ctx, req.(*EmailOtpPrimaryKey))
	}
	return interceptor(ctx, in, info, handler)
}

// EmailOtpService_ServiceDesc is the grpc.ServiceDesc for EmailOtpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EmailOtpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "auth_service.EmailOtpService",
	HandlerType: (*EmailOtpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _EmailOtpService_Create_Handler,
		},
		{
			MethodName: "GetEmailByID",
			Handler:    _EmailOtpService_GetEmailByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "email.proto",
}
